language: node_js
os: linux
node_js:
  - 14

services:
  - docker

before_install:
  - npm i -g npm

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - VERSION=$(node -p "require('./package.json').version")

script:
  - npm run build
  - docker build -t genshinwishes/genshin-wishes-ui:$VERSION  .
  - docker push genshinwishes/genshin-wishes-ui:$VERSION

before_deploy:
  - git tag $VERSION

deploy:
  provider: releases
